modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-3.0"

[[mods]]
modId = "russianmetro"
version = "@version@"
displayName = "MTR Russian Metro Addon"
authors = "WerySkok"
description = "A Russian Metro Addon for the Minecraft Transit Railway mod"
logoFile = "icon.png"

[[dependencies.russianmetro]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.russianmetro]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"

[[dependencies.russianmetro]]
modId = "mtr"
mandatory = true
versionRange = "[4.0.0-beta.14,4.1)"
ordering = "AFTER"
side = "BOTH"
